# Generated by Django 5.0.3 on 2024-04-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_post_comment_post_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comment_count',
        ),
    ]
