# Generated by Django 5.0.3 on 2024-04-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_rename_comment_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='has_commented',
            field=models.BooleanField(default=False),
        ),
    ]
